### PR TITLE
Fix text overlap bug

### PR DESCRIPTION
**Pull request by chancefeick**

### CODE REVIEW

**Comment by MichMich** [comment]
This gives an issue with the possibility to change the character spacing. (Probably the reason why you took it out?). I'll try to fix it in the master. Stay tuned.

**Comment by MichMich** [comment]
Fixed in commit: https://github.com/MichMich/XMCircleType/commit/56bbe43355a7f5e53911597ecf3edfd04809edc6

**Comment by chancefeick** [comment]
While my fix did solve the issue for the default character spacing, you are right that it does not handle the changing of character spacing. I wanted to bring attention to the text overlap bug.

There appears to be an issue with how you calculate the character position. It does not take into consideration the character spacing. When iterating through the string characters, logging the current character position and circumference confirm this.

**Comment by MichMich** [comment]
Can you give an example of the overlap bug? (which string, and settings are you trying?)

**Pull request closed without merging**
